# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-03 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0009_auto_20160613_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='OggInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogginfo_prov', models.CharField(max_length=16, verbose_name='\u7701\u7b80\u79f0')),
                ('ogginfo_type', models.CharField(max_length=64, verbose_name='OGG\u7c7b\u578b')),
                ('ogginfo_host', models.GenericIPAddressField(verbose_name='\u4e3b\u673aIP')),
                ('ogginfo_status', models.TextField(max_length=512, verbose_name='\u8fdb\u7a0b\u72b6\u6001')),
                ('ogginfo_detail', models.TextField(max_length=1024, verbose_name='\u8fdb\u7a0b\u660e\u7ec6')),
                ('ogginfo_diskspace', models.TextField(max_length=1024, verbose_name='\u78c1\u76d8\u7a7a\u95f4')),
                ('ogginfo_tablespace', models.TextField(max_length=1024, verbose_name='\u5e93\u8868\u7a7a\u95f4')),
                ('ogginfo_delay', models.CharField(max_length=16, verbose_name='\u662f\u5426\u5ef6\u8fdf')),
                ('ogginfo_suspend', models.CharField(max_length=16, verbose_name='\u662f\u5426\u6302\u8d77')),
                ('ogginfo_createtime', models.DateField(verbose_name='\u5de1\u68c0\u65f6\u95f4')),
            ],
        ),
    ]
