# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-04 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0010_ogginfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparecount_prov', models.CharField(max_length=16, verbose_name='\u7701\u7b80\u79f0')),
                ('comparecount_type', models.CharField(max_length=64, verbose_name='\u7c7b\u578b')),
                ('comparecount_tab', models.CharField(max_length=64, verbose_name='\u8868\u540d')),
                ('comparecount_src', models.TextField(max_length=512, verbose_name='\u6e90\u7aef\u6570\u91cf')),
                ('comparecount_dst', models.TextField(max_length=1024, verbose_name='\u76ee\u6807\u6570\u91cf')),
                ('comparecount_diff', models.TextField(max_length=1024, verbose_name='\u5dee\u5f02\u6570\u91cf')),
                ('comparecount_date', models.DateField(verbose_name='\u5de1\u68c0\u65f6\u95f4')),
            ],
        ),
    ]
